### ISSUE TITLE
error of bytes array to HEX 

### ISSUE THREAD

**Issue by MIMIEYES** [super053/web3objc#1]
First of all, thank the author for the open source code, which greatly saved the development cost, thank you very much.

I found a problem. In a function that converts a variable bytes array to HEX, `CVETHABIArgument#fromDataNoLength`, if the length of the array exceeds 32, assuming the length is 37, then the return value of this function is the HEX of the last 5 bytes and the first 32 Bytes of data are lost.

```retStr = [self argumentWithRearPadding:[argSubData dataDirectString]];``` is changed to
```retStr = [NSString stringWithFormat:@"%@%@", retStr, [self argumentWithRearPadding:[argSubData dataDirectString]]];``` to solve the problem.

The code location is [here](https://github.com/super053/web3objc/blob/master/Web3Objc/CVETHLib/ABI/CVETHABIArgument.m#L98).

**Comment by super053** [comment]
Thanks comment. I will edit this code.

**Comment by super053** [comment]
commit [this](https://github.com/super053/web3objc/commit/626cd592d800758de4dec2ed772eb0b543d284d5)
